# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'citeGUI.ui'
#
# Created: Sun Nov 29 20:32:22 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Cite(object):
    def setupUi(self, Cite):
        Cite.setObjectName(_fromUtf8("Cite"))
        Cite.resize(750, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Cite.sizePolicy().hasHeightForWidth())
        Cite.setSizePolicy(sizePolicy)
        Cite.setMinimumSize(QtCore.QSize(750, 500))
        self.centralWidget = QtGui.QWidget(Cite)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.searchTab = QtGui.QWidget()
        self.searchTab.setObjectName(_fromUtf8("searchTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.searchTab)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.searchQuery = QtGui.QPlainTextEdit(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchQuery.sizePolicy().hasHeightForWidth())
        self.searchQuery.setSizePolicy(sizePolicy)
        self.searchQuery.setMinimumSize(QtCore.QSize(0, 80))
        self.searchQuery.setMaximumSize(QtCore.QSize(16777215, 80))
        self.searchQuery.setObjectName(_fromUtf8("searchQuery"))
        self.verticalLayout_2.addWidget(self.searchQuery)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_5 = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.arxiv = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arxiv.sizePolicy().hasHeightForWidth())
        self.arxiv.setSizePolicy(sizePolicy)
        self.arxiv.setMinimumSize(QtCore.QSize(90, 0))
        self.arxiv.setObjectName(_fromUtf8("arxiv"))
        self.horizontalLayout_4.addWidget(self.arxiv)
        self.arxivExport = QtGui.QPushButton(self.groupBox_5)
        self.arxivExport.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arxivExport.sizePolicy().hasHeightForWidth())
        self.arxivExport.setSizePolicy(sizePolicy)
        self.arxivExport.setMinimumSize(QtCore.QSize(60, 0))
        self.arxivExport.setObjectName(_fromUtf8("arxivExport"))
        self.horizontalLayout_4.addWidget(self.arxivExport)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.msn = QtGui.QPushButton(self.groupBox_6)
        self.msn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msn.sizePolicy().hasHeightForWidth())
        self.msn.setSizePolicy(sizePolicy)
        self.msn.setMinimumSize(QtCore.QSize(100, 0))
        self.msn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.msn.setObjectName(_fromUtf8("msn"))
        self.horizontalLayout_8.addWidget(self.msn)
        self.mrl = QtGui.QPushButton(self.groupBox_6)
        self.mrl.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrl.sizePolicy().hasHeightForWidth())
        self.mrl.setSizePolicy(sizePolicy)
        self.mrl.setMinimumSize(QtCore.QSize(90, 0))
        self.mrl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.mrl.setObjectName(_fromUtf8("mrl"))
        self.horizontalLayout_8.addWidget(self.mrl)
        self.mref = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mref.sizePolicy().hasHeightForWidth())
        self.mref.setSizePolicy(sizePolicy)
        self.mref.setMinimumSize(QtCore.QSize(60, 0))
        self.mref.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mref.setObjectName(_fromUtf8("mref"))
        self.horizontalLayout_8.addWidget(self.mref)
        self.msnAuthor = QtGui.QPushButton(self.groupBox_6)
        self.msnAuthor.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msnAuthor.sizePolicy().hasHeightForWidth())
        self.msnAuthor.setSizePolicy(sizePolicy)
        self.msnAuthor.setMinimumSize(QtCore.QSize(70, 0))
        self.msnAuthor.setMaximumSize(QtCore.QSize(70, 16777215))
        self.msnAuthor.setCheckable(False)
        self.msnAuthor.setObjectName(_fromUtf8("msnAuthor"))
        self.horizontalLayout_8.addWidget(self.msnAuthor)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.zbl = QtGui.QPushButton(self.groupBox_7)
        self.zbl.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zbl.sizePolicy().hasHeightForWidth())
        self.zbl.setSizePolicy(sizePolicy)
        self.zbl.setMinimumSize(QtCore.QSize(85, 0))
        self.zbl.setMaximumSize(QtCore.QSize(85, 16777215))
        self.zbl.setObjectName(_fromUtf8("zbl"))
        self.horizontalLayout_10.addWidget(self.zbl)
        self.zblAuthor = QtGui.QPushButton(self.groupBox_7)
        self.zblAuthor.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zblAuthor.sizePolicy().hasHeightForWidth())
        self.zblAuthor.setSizePolicy(sizePolicy)
        self.zblAuthor.setMinimumSize(QtCore.QSize(70, 0))
        self.zblAuthor.setMaximumSize(QtCore.QSize(70, 16777215))
        self.zblAuthor.setObjectName(_fromUtf8("zblAuthor"))
        self.horizontalLayout_10.addWidget(self.zblAuthor)
        self.horizontalLayout.addWidget(self.groupBox_7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.groupBox_8 = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.openInResults = QtGui.QPushButton(self.groupBox_8)
        self.openInResults.setObjectName(_fromUtf8("openInResults"))
        self.horizontalLayout_11.addWidget(self.openInResults)
        self.reformat = QtGui.QPushButton(self.groupBox_8)
        self.reformat.setObjectName(_fromUtf8("reformat"))
        self.horizontalLayout_11.addWidget(self.reformat)
        self.showBibtex = QtGui.QPushButton(self.groupBox_8)
        self.showBibtex.setObjectName(_fromUtf8("showBibtex"))
        self.horizontalLayout_11.addWidget(self.showBibtex)
        self.horizontalLayout_9.addWidget(self.groupBox_8)
        self.groupBox_10 = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.formatBibtex = QtGui.QPushButton(self.groupBox_10)
        self.formatBibtex.setObjectName(_fromUtf8("formatBibtex"))
        self.horizontalLayout_12.addWidget(self.formatBibtex)
        self.allThree = QtGui.QPushButton(self.groupBox_10)
        self.allThree.setEnabled(True)
        self.allThree.setMinimumSize(QtCore.QSize(80, 0))
        self.allThree.setObjectName(_fromUtf8("allThree"))
        self.horizontalLayout_12.addWidget(self.allThree)
        self.horizontalLayout_9.addWidget(self.groupBox_10)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.quickResults = QtGui.QTextBrowser(self.searchTab)
        self.quickResults.setReadOnly(True)
        self.quickResults.setOpenExternalLinks(True)
        self.quickResults.setObjectName(_fromUtf8("quickResults"))
        self.verticalLayout_2.addWidget(self.quickResults)
        self.tabWidget.addTab(self.searchTab, _fromUtf8(""))
        self.resultsTab = QtGui.QWidget()
        self.resultsTab.setEnabled(True)
        self.resultsTab.setObjectName(_fromUtf8("resultsTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.resultsTab)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.savedReformat = QtGui.QPushButton(self.resultsTab)
        self.savedReformat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedReformat.sizePolicy().hasHeightForWidth())
        self.savedReformat.setSizePolicy(sizePolicy)
        self.savedReformat.setObjectName(_fromUtf8("savedReformat"))
        self.horizontalLayout_13.addWidget(self.savedReformat)
        self.savedShowBibtex = QtGui.QPushButton(self.resultsTab)
        self.savedShowBibtex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedShowBibtex.sizePolicy().hasHeightForWidth())
        self.savedShowBibtex.setSizePolicy(sizePolicy)
        self.savedShowBibtex.setObjectName(_fromUtf8("savedShowBibtex"))
        self.horizontalLayout_13.addWidget(self.savedShowBibtex)
        self.saveLatex = QtGui.QPushButton(self.resultsTab)
        self.saveLatex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveLatex.sizePolicy().hasHeightForWidth())
        self.saveLatex.setSizePolicy(sizePolicy)
        self.saveLatex.setObjectName(_fromUtf8("saveLatex"))
        self.horizontalLayout_13.addWidget(self.saveLatex)
        self.saveBibtex = QtGui.QPushButton(self.resultsTab)
        self.saveBibtex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBibtex.sizePolicy().hasHeightForWidth())
        self.saveBibtex.setSizePolicy(sizePolicy)
        self.saveBibtex.setObjectName(_fromUtf8("saveBibtex"))
        self.horizontalLayout_13.addWidget(self.saveBibtex)
        self.loadBibtex = QtGui.QPushButton(self.resultsTab)
        self.loadBibtex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBibtex.sizePolicy().hasHeightForWidth())
        self.loadBibtex.setSizePolicy(sizePolicy)
        self.loadBibtex.setObjectName(_fromUtf8("loadBibtex"))
        self.horizontalLayout_13.addWidget(self.loadBibtex)
        self.openInBatch = QtGui.QPushButton(self.resultsTab)
        self.openInBatch.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openInBatch.sizePolicy().hasHeightForWidth())
        self.openInBatch.setSizePolicy(sizePolicy)
        self.openInBatch.setObjectName(_fromUtf8("openInBatch"))
        self.horizontalLayout_13.addWidget(self.openInBatch)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.resultsTabs = QtGui.QTabWidget(self.resultsTab)
        self.resultsTabs.setTabPosition(QtGui.QTabWidget.North)
        self.resultsTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.resultsTabs.setDocumentMode(True)
        self.resultsTabs.setTabsClosable(True)
        self.resultsTabs.setMovable(True)
        
        self.resultsTabs.setObjectName(_fromUtf8("resultsTabs"))
        self.emptyResults = QtGui.QWidget()
        self.emptyResults.setObjectName(_fromUtf8("emptyResults"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.emptyResults)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.emptyText = QtGui.QTextBrowser(self.emptyResults)
        self.emptyText.setEnabled(True)
        self.emptyText.setUndoRedoEnabled(False)
        self.emptyText.setReadOnly(True)
        self.emptyText.setObjectName(_fromUtf8("emptyText"))
        self.horizontalLayout_3.addWidget(self.emptyText)
        self.resultsTabs.addTab(self.emptyResults, _fromUtf8(""))
        self.verticalLayout.addWidget(self.resultsTabs)
        self.tabWidget.addTab(self.resultsTab, _fromUtf8(""))
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setObjectName(_fromUtf8("optionsTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.optionsTab)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.optionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(650, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.keepBibitems = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepBibitems.sizePolicy().hasHeightForWidth())
        self.keepBibitems.setSizePolicy(sizePolicy)
        self.keepBibitems.setChecked(True)
        self.keepBibitems.setObjectName(_fromUtf8("keepBibitems"))
        self.gridLayout_2.addWidget(self.keepBibitems, 0, 9, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 10, 1, 1)
        self.bibtexOut = QtGui.QCheckBox(self.groupBox_2)
        self.bibtexOut.setObjectName(_fromUtf8("bibtexOut"))
        self.gridLayout_2.addWidget(self.bibtexOut, 0, 1, 1, 1)
        self.genBibitems = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genBibitems.sizePolicy().hasHeightForWidth())
        self.genBibitems.setSizePolicy(sizePolicy)
        self.genBibitems.setChecked(True)
        self.genBibitems.setObjectName(_fromUtf8("genBibitems"))
        self.gridLayout_2.addWidget(self.genBibitems, 0, 8, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 0, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 3, 1, 1)
        self.sortBy = QtGui.QComboBox(self.groupBox_2)
        self.sortBy.setObjectName(_fromUtf8("sortBy"))
        self.sortBy.addItem(_fromUtf8(""))
        self.sortBy.addItem(_fromUtf8(""))
        self.sortBy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.sortBy, 0, 4, 1, 2)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        self.defaultArxiv = QtGui.QComboBox(self.groupBox_2)
        self.defaultArxiv.setEnabled(False)
        self.defaultArxiv.setObjectName(_fromUtf8("defaultArxiv"))
        self.defaultArxiv.addItem(_fromUtf8(""))
        self.defaultArxiv.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.defaultArxiv, 1, 2, 1, 4)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 7, 1, 1)
        self.defaultAMS = QtGui.QComboBox(self.groupBox_2)
        self.defaultAMS.setEnabled(False)
        self.defaultAMS.setObjectName(_fromUtf8("defaultAMS"))
        self.defaultAMS.addItem(_fromUtf8(""))
        self.defaultAMS.addItem(_fromUtf8(""))
        self.defaultAMS.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.defaultAMS, 1, 8, 1, 2)
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 1, 6, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.optionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(650, 0))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setMargin(5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.authorStyle = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorStyle.sizePolicy().hasHeightForWidth())
        self.authorStyle.setSizePolicy(sizePolicy)
        self.authorStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.authorStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.authorStyle.setObjectName(_fromUtf8("authorStyle"))
        self.gridLayout_3.addWidget(self.authorStyle, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 4, 1, 1)
        self.journalStyle = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journalStyle.sizePolicy().hasHeightForWidth())
        self.journalStyle.setSizePolicy(sizePolicy)
        self.journalStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.journalStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.journalStyle.setText(_fromUtf8(""))
        self.journalStyle.setObjectName(_fromUtf8("journalStyle"))
        self.gridLayout_3.addWidget(self.journalStyle, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.titleStyle = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleStyle.sizePolicy().hasHeightForWidth())
        self.titleStyle.setSizePolicy(sizePolicy)
        self.titleStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.titleStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.titleStyle.setObjectName(_fromUtf8("titleStyle"))
        self.gridLayout_3.addWidget(self.titleStyle, 0, 1, 1, 1)
        self.bibitemStyle = QtGui.QComboBox(self.groupBox_3)
        self.bibitemStyle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bibitemStyle.sizePolicy().hasHeightForWidth())
        self.bibitemStyle.setSizePolicy(sizePolicy)
        self.bibitemStyle.setObjectName(_fromUtf8("bibitemStyle"))
        self.bibitemStyle.addItem(_fromUtf8(""))
        self.bibitemStyle.addItem(_fromUtf8(""))
        self.bibitemStyle.addItem(_fromUtf8(""))
        self.bibitemStyle.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.bibitemStyle, 1, 6, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.volumeStyle = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeStyle.sizePolicy().hasHeightForWidth())
        self.volumeStyle.setSizePolicy(sizePolicy)
        self.volumeStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.volumeStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.volumeStyle.setObjectName(_fromUtf8("volumeStyle"))
        self.gridLayout_3.addWidget(self.volumeStyle, 0, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.numberStyle = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberStyle.sizePolicy().hasHeightForWidth())
        self.numberStyle.setSizePolicy(sizePolicy)
        self.numberStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.numberStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.numberStyle.setObjectName(_fromUtf8("numberStyle"))
        self.gridLayout_3.addWidget(self.numberStyle, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.bst = QtGui.QComboBox(self.groupBox_3)
        self.bst.setEnabled(False)
        self.bst.setObjectName(_fromUtf8("bst"))
        self.bst.addItem(_fromUtf8(""))
        self.bst.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.bst, 1, 3, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 5, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.optionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.searchArxiv = QtGui.QComboBox(self.groupBox)
        self.searchArxiv.setObjectName(_fromUtf8("searchArxiv"))
        self.searchArxiv.addItem(_fromUtf8(""))
        self.searchArxiv.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.searchArxiv, 12, 1, 1, 3)
        self.searchCount = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchCount.sizePolicy().hasHeightForWidth())
        self.searchCount.setSizePolicy(sizePolicy)
        self.searchCount.setMinimumSize(QtCore.QSize(50, 0))
        self.searchCount.setMaximumSize(QtCore.QSize(50, 16777215))
        self.searchCount.setMinimum(1)
        self.searchCount.setMaximum(999)
        self.searchCount.setProperty("value", 10)
        self.searchCount.setObjectName(_fromUtf8("searchCount"))
        self.gridLayout.addWidget(self.searchCount, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(90, 0))
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(90, 0))
        self.label_16.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 12, 0, 1, 1)
        self.searchMRZbl = QtGui.QComboBox(self.groupBox)
        self.searchMRZbl.setObjectName(_fromUtf8("searchMRZbl"))
        self.searchMRZbl.addItem(_fromUtf8(""))
        self.searchMRZbl.addItem(_fromUtf8(""))
        self.searchMRZbl.addItem(_fromUtf8(""))
        self.searchMRZbl.addItem(_fromUtf8(""))
        self.searchMRZbl.addItem(_fromUtf8(""))
        self.searchMRZbl.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.searchMRZbl, 9, 1, 1, 3)
        self.searchIncludeDOIURL = QtGui.QComboBox(self.groupBox)
        self.searchIncludeDOIURL.setObjectName(_fromUtf8("searchIncludeDOIURL"))
        self.searchIncludeDOIURL.addItem(_fromUtf8(""))
        self.searchIncludeDOIURL.addItem(_fromUtf8(""))
        self.searchIncludeDOIURL.addItem(_fromUtf8(""))
        self.searchIncludeDOIURL.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.searchIncludeDOIURL, 10, 1, 1, 3)
        self.label_15 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(90, 0))
        self.label_15.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.searchDOIURL = QtGui.QComboBox(self.groupBox)
        self.searchDOIURL.setObjectName(_fromUtf8("searchDOIURL"))
        self.searchDOIURL.addItem(_fromUtf8(""))
        self.searchDOIURL.addItem(_fromUtf8(""))
        self.searchDOIURL.addItem(_fromUtf8(""))
        self.searchDOIURL.addItem(_fromUtf8(""))
        self.searchDOIURL.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.searchDOIURL, 11, 1, 1, 3)
        self.searchMrefWithZbl = QtGui.QCheckBox(self.groupBox)
        self.searchMrefWithZbl.setChecked(True)
        self.searchMrefWithZbl.setObjectName(_fromUtf8("searchMrefWithZbl"))
        self.gridLayout.addWidget(self.searchMrefWithZbl, 3, 0, 1, 2)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_9 = QtGui.QGroupBox(self.optionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_5.setMargin(5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.batchFindZbl = QtGui.QCheckBox(self.groupBox_9)
        self.batchFindZbl.setEnabled(False)
        self.batchFindZbl.setObjectName(_fromUtf8("batchFindZbl"))
        self.gridLayout_5.addWidget(self.batchFindZbl, 2, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(90, 0))
        self.label_20.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 2)
        self.batchCount = QtGui.QSpinBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchCount.sizePolicy().hasHeightForWidth())
        self.batchCount.setSizePolicy(sizePolicy)
        self.batchCount.setMinimumSize(QtCore.QSize(50, 0))
        self.batchCount.setMaximumSize(QtCore.QSize(50, 16777215))
        self.batchCount.setMinimum(1)
        self.batchCount.setMaximum(10)
        self.batchCount.setProperty("value", 3)
        self.batchCount.setObjectName(_fromUtf8("batchCount"))
        self.gridLayout_5.addWidget(self.batchCount, 0, 2, 1, 1)
        self.batchDOIURL = QtGui.QComboBox(self.groupBox_9)
        self.batchDOIURL.setObjectName(_fromUtf8("batchDOIURL"))
        self.gridLayout_5.addWidget(self.batchDOIURL, 6, 1, 1, 2)
        self.arxivFirst = QtGui.QCheckBox(self.groupBox_9)
        self.arxivFirst.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arxivFirst.sizePolicy().hasHeightForWidth())
        self.arxivFirst.setSizePolicy(sizePolicy)
        self.arxivFirst.setObjectName(_fromUtf8("arxivFirst"))
        self.gridLayout_5.addWidget(self.arxivFirst, 1, 0, 1, 1)
        self.batchArxiv = QtGui.QComboBox(self.groupBox_9)
        self.batchArxiv.setObjectName(_fromUtf8("batchArxiv"))
        self.gridLayout_5.addWidget(self.batchArxiv, 7, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(90, 0))
        self.label_18.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 4, 0, 1, 1)
        self.batchFindMR = QtGui.QCheckBox(self.groupBox_9)
        self.batchFindMR.setChecked(True)
        self.batchFindMR.setObjectName(_fromUtf8("batchFindMR"))
        self.gridLayout_5.addWidget(self.batchFindMR, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(90, 0))
        self.label_19.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 5, 0, 1, 1)
        self.batchIncludeDOIURL = QtGui.QComboBox(self.groupBox_9)
        self.batchIncludeDOIURL.setObjectName(_fromUtf8("batchIncludeDOIURL"))
        self.gridLayout_5.addWidget(self.batchIncludeDOIURL, 5, 1, 1, 2)
        self.batchMRZbl = QtGui.QComboBox(self.groupBox_9)
        self.batchMRZbl.setObjectName(_fromUtf8("batchMRZbl"))
        self.gridLayout_5.addWidget(self.batchMRZbl, 4, 1, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_9)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.tabWidget.addTab(self.optionsTab, _fromUtf8(""))
        self.batchTab = QtGui.QWidget()
        self.batchTab.setEnabled(True)
        self.batchTab.setObjectName(_fromUtf8("batchTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.batchTab)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setMargin(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_21 = QtGui.QLabel(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.separator = QtGui.QComboBox(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separator.sizePolicy().hasHeightForWidth())
        self.separator.setSizePolicy(sizePolicy)
        self.separator.setMinimumSize(QtCore.QSize(130, 0))
        self.separator.setMaximumSize(QtCore.QSize(130, 16777215))
        self.separator.setObjectName(_fromUtf8("separator"))
        self.separator.addItem(_fromUtf8(""))
        self.separator.addItem(_fromUtf8(""))
        self.separator.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.separator)
        self.label_22 = QtGui.QLabel(self.batchTab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_2.addWidget(self.label_22)
        self.batchFetcher = QtGui.QComboBox(self.batchTab)
        self.batchFetcher.setObjectName(_fromUtf8("batchFetcher"))
        self.batchFetcher.addItem(_fromUtf8(""))
        self.batchFetcher.addItem(_fromUtf8(""))
        self.batchFetcher.addItem(_fromUtf8(""))
        self.batchFetcher.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.batchFetcher)
        self.line_4 = QtGui.QFrame(self.batchTab)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.label_23 = QtGui.QLabel(self.batchTab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_2.addWidget(self.label_23)
        self.batchRun = QtGui.QPushButton(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRun.sizePolicy().hasHeightForWidth())
        self.batchRun.setSizePolicy(sizePolicy)
        self.batchRun.setMinimumSize(QtCore.QSize(100, 0))
        self.batchRun.setMaximumSize(QtCore.QSize(100, 16777215))
        self.batchRun.setObjectName(_fromUtf8("batchRun"))
        self.horizontalLayout_2.addWidget(self.batchRun)
        self.batchRunSelected = QtGui.QPushButton(self.batchTab)
        self.batchRunSelected.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRunSelected.sizePolicy().hasHeightForWidth())
        self.batchRunSelected.setSizePolicy(sizePolicy)
        self.batchRunSelected.setMinimumSize(QtCore.QSize(100, 0))
        self.batchRunSelected.setMaximumSize(QtCore.QSize(100, 16777215))
        self.batchRunSelected.setObjectName(_fromUtf8("batchRunSelected"))
        self.horizontalLayout_2.addWidget(self.batchRunSelected)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.batchOpenInResults = QtGui.QPushButton(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchOpenInResults.sizePolicy().hasHeightForWidth())
        self.batchOpenInResults.setSizePolicy(sizePolicy)
        self.batchOpenInResults.setMinimumSize(QtCore.QSize(120, 0))
        self.batchOpenInResults.setMaximumSize(QtCore.QSize(120, 16777215))
        self.batchOpenInResults.setObjectName(_fromUtf8("batchOpenInResults"))
        self.horizontalLayout_7.addWidget(self.batchOpenInResults)
        self.batchOpenOptions = QtGui.QComboBox(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchOpenOptions.sizePolicy().hasHeightForWidth())
        self.batchOpenOptions.setSizePolicy(sizePolicy)
        self.batchOpenOptions.setMinimumSize(QtCore.QSize(80, 0))
        self.batchOpenOptions.setMaximumSize(QtCore.QSize(80, 16777215))
        self.batchOpenOptions.setObjectName(_fromUtf8("batchOpenOptions"))
        self.batchOpenOptions.addItem(_fromUtf8(""))
        self.batchOpenOptions.addItem(_fromUtf8(""))
        self.batchOpenOptions.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.batchOpenOptions)
        self.batchRemove = QtGui.QPushButton(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRemove.sizePolicy().hasHeightForWidth())
        self.batchRemove.setSizePolicy(sizePolicy)
        self.batchRemove.setMinimumSize(QtCore.QSize(80, 0))
        self.batchRemove.setMaximumSize(QtCore.QSize(80, 16777215))
        self.batchRemove.setObjectName(_fromUtf8("batchRemove"))
        self.horizontalLayout_7.addWidget(self.batchRemove)
        self.batchRemoveOptions = QtGui.QComboBox(self.batchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRemoveOptions.sizePolicy().hasHeightForWidth())
        self.batchRemoveOptions.setSizePolicy(sizePolicy)
        self.batchRemoveOptions.setMinimumSize(QtCore.QSize(150, 0))
        self.batchRemoveOptions.setMaximumSize(QtCore.QSize(150, 16777215))
        self.batchRemoveOptions.setObjectName(_fromUtf8("batchRemoveOptions"))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.batchRemoveOptions.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.batchRemoveOptions)
        self.line_5 = QtGui.QFrame(self.batchTab)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_7.addWidget(self.line_5)
        self.pushButton_5 = QtGui.QPushButton(self.batchTab)
        self.pushButton_5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_4 = QtGui.QPushButton(self.batchTab)
        self.pushButton_4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.batchEdit = QtGui.QTextEdit(self.batchTab)
        self.batchEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.batchEdit.setObjectName(_fromUtf8("batchEdit"))
        self.verticalLayout_7.addWidget(self.batchEdit)
        self.tabWidget.addTab(self.batchTab, _fromUtf8(""))
        self.helpTab = QtGui.QWidget()
        self.helpTab.setObjectName(_fromUtf8("helpTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.helpTab)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.helpText = QtGui.QTextBrowser(self.helpTab)
        self.helpText.setOpenExternalLinks(True)
        self.helpText.setObjectName(_fromUtf8("helpText"))
        self.verticalLayout_4.addWidget(self.helpText)
        self.tabWidget.addTab(self.helpTab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget)
        Cite.setCentralWidget(self.centralWidget)

        self.retranslateUi(Cite)
        self.tabWidget.setCurrentIndex(3)
        self.resultsTabs.setCurrentIndex(0)
        self.searchMRZbl.setCurrentIndex(3)
        self.searchIncludeDOIURL.setCurrentIndex(1)
        self.searchDOIURL.setCurrentIndex(3)
        self.batchMRZbl.setCurrentIndex(-1)
        self.separator.setCurrentIndex(2)
        self.batchOpenOptions.setCurrentIndex(2)
        self.batchRemoveOptions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Cite)

    def retranslateUi(self, Cite):
        Cite.setWindowTitle(_translate("Cite", "Cite", None))
        self.searchQuery.setToolTip(_translate("Cite", "<html><head/><body><p>Supports and/or/not operator, parentheses and field specifiers.</p><p>For example au:, ti:, py: denote title, author and publication year fields. For the complete list of fields see Help.</p><p>New line indicates a new field, which can sometimes be guessed. E.g. 2005-2011 or 2005 will be treated as publication year.</p><p>Operators and/or/not at the end or beginning of a line are treated as connectors for the whole fields/lines.</p><p>Fully formed LaTex citation or BibTex record can also be used.</p></body></html>", None))
        self.groupBox_5.setTitle(_translate("Cite", "arXiv", None))
        self.arxiv.setText(_translate("Cite", "arXiv front", None))
        self.arxivExport.setText(_translate("Cite", "Export", None))
        self.groupBox_6.setTitle(_translate("Cite", "MSN", None))
        self.msn.setText(_translate("Cite", "MathSciNet", None))
        self.mrl.setText(_translate("Cite", "MRLookup", None))
        self.mref.setText(_translate("Cite", "MRef", None))
        self.msnAuthor.setText(_translate("Cite", "Author", None))
        self.groupBox_7.setTitle(_translate("Cite", "Zentralblatt", None))
        self.zbl.setText(_translate("Cite", "zbMATH", None))
        self.zblAuthor.setText(_translate("Cite", "Author", None))
        self.groupBox_8.setTitle(_translate("Cite", "Last result", None))
        self.openInResults.setText(_translate("Cite", "Open in Saved", None))
        self.reformat.setText(_translate("Cite", "Reformat", None))
        self.showBibtex.setText(_translate("Cite", "Show  BibTex", None))
        self.groupBox_10.setTitle(_translate("Cite", "Other", None))
        self.formatBibtex.setText(_translate("Cite", "BibTex on query", None))
        self.allThree.setText(_translate("Cite", "arXiv + MSN + Zbl", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchTab), _translate("Cite", "Search", None))
        self.savedReformat.setText(_translate("Cite", "Reformat", None))
        self.savedShowBibtex.setText(_translate("Cite", "Show BibTex", None))
        self.saveLatex.setText(_translate("Cite", "Save LaTeX", None))
        self.saveBibtex.setText(_translate("Cite", "Save BibTex", None))
        self.loadBibtex.setText(_translate("Cite", "Load BibTex", None))
        self.openInBatch.setText(_translate("Cite", "Open in Batch", None))
        self.emptyText.setHtml(_translate("Cite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click &quot;Open in Saved&quot; in the search or batch tab for the search results to appear here.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.emptyResults), _translate("Cite", "No results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), _translate("Cite", "Saved", None))
        self.groupBox_2.setTitle(_translate("Cite", "General", None))
        self.keepBibitems.setText(_translate("Cite", "keep existing", None))
        self.bibtexOut.setText(_translate("Cite", "BibTex output", None))
        self.genBibitems.setText(_translate("Cite", "generate", None))
        self.label_12.setText(_translate("Cite", "Bibitems:", None))
        self.label_13.setText(_translate("Cite", "Default arXiv", None))
        self.label_17.setText(_translate("Cite", "Sort", None))
        self.sortBy.setItemText(0, _translate("Cite", "newest first", None))
        self.sortBy.setItemText(1, _translate("Cite", "oldest first", None))
        self.sortBy.setItemText(2, _translate("Cite", "by name", None))
        self.defaultArxiv.setItemText(0, _translate("Cite", "UCDavis front", None))
        self.defaultArxiv.setItemText(1, _translate("Cite", "export", None))
        self.label_3.setText(_translate("Cite", "Default MSN", None))
        self.defaultAMS.setItemText(0, _translate("Cite", "Automatic", None))
        self.defaultAMS.setItemText(1, _translate("Cite", "MathSciNet", None))
        self.defaultAMS.setItemText(2, _translate("Cite", "MRLookup", None))
        self.groupBox_3.setTitle(_translate("Cite", "Style", None))
        self.authorStyle.setText(_translate("Cite", "textbf", None))
        self.label_9.setText(_translate("Cite", "Volume", None))
        self.label_8.setText(_translate("Cite", "Journal", None))
        self.label_6.setText(_translate("Cite", "Title", None))
        self.titleStyle.setText(_translate("Cite", "textit", None))
        self.bibitemStyle.setItemText(0, _translate("Cite", "{initials}", None))
        self.bibitemStyle.setItemText(1, _translate("Cite", "[initials]{initials}", None))
        self.bibitemStyle.setItemText(2, _translate("Cite", "{id}", None))
        self.bibitemStyle.setItemText(3, _translate("Cite", "[initials]{id}", None))
        self.label_7.setText(_translate("Cite", "Author", None))
        self.volumeStyle.setText(_translate("Cite", "textbf", None))
        self.label_10.setText(_translate("Cite", "Number", None))
        self.numberStyle.setText(_translate("Cite", "textit", None))
        self.label_5.setText(_translate("Cite", "Order", None))
        self.bst.setItemText(0, _translate("Cite", "amsplain", None))
        self.bst.setItemText(1, _translate("Cite", "plain", None))
        self.label_11.setText(_translate("Cite", "Labels", None))
        self.groupBox.setTitle(_translate("Cite", "Search options", None))
        self.searchArxiv.setItemText(0, _translate("Cite", "Include", None))
        self.searchArxiv.setItemText(1, _translate("Cite", "Exclude", None))
        self.label.setText(_translate("Cite", "Maximal number of  matches", None))
        self.label_14.setText(_translate("Cite", "MR# / Zbl#", None))
        self.label_16.setText(_translate("Cite", "arXiv#", None))
        self.searchMRZbl.setItemText(0, _translate("Cite", "Both", None))
        self.searchMRZbl.setItemText(1, _translate("Cite", "MR#", None))
        self.searchMRZbl.setItemText(2, _translate("Cite", "Zbl#", None))
        self.searchMRZbl.setItemText(3, _translate("Cite", "Zbl# if no MR#", None))
        self.searchMRZbl.setItemText(4, _translate("Cite", "MR# if no Zbl#", None))
        self.searchMRZbl.setItemText(5, _translate("Cite", "Neither", None))
        self.searchIncludeDOIURL.setItemText(0, _translate("Cite", "Include", None))
        self.searchIncludeDOIURL.setItemText(1, _translate("Cite", "Only if no MR#/Zbl#", None))
        self.searchIncludeDOIURL.setItemText(2, _translate("Cite", "Only if no MR#/Zbl#/arXiv#", None))
        self.searchIncludeDOIURL.setItemText(3, _translate("Cite", "Exclude", None))
        self.label_15.setText(_translate("Cite", "DOI# / URL", None))
        self.searchDOIURL.setItemText(0, _translate("Cite", "Both", None))
        self.searchDOIURL.setItemText(1, _translate("Cite", "DOI#", None))
        self.searchDOIURL.setItemText(2, _translate("Cite", "URL", None))
        self.searchDOIURL.setItemText(3, _translate("Cite", "URL if different than DOI#", None))
        self.searchDOIURL.setItemText(4, _translate("Cite", "DOI# as URL", None))
        self.searchMrefWithZbl.setText(_translate("Cite", "MRef with zbMATH", None))
        self.groupBox_9.setTitle(_translate("Cite", "Batch/Terminal options", None))
        self.batchFindZbl.setText(_translate("Cite", "try to find Zbl#", None))
        self.label_20.setText(_translate("Cite", "arXiv#", None))
        self.label_2.setText(_translate("Cite", "Maximal number of matches", None))
        self.arxivFirst.setText(_translate("Cite", "arXiv first", None))
        self.label_18.setText(_translate("Cite", "MR# / Zbl#", None))
        self.batchFindMR.setText(_translate("Cite", "try to find MR#", None))
        self.label_19.setText(_translate("Cite", "DOI# / URL", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), _translate("Cite", "Options", None))
        self.label_21.setText(_translate("Cite", "Separator", None))
        self.separator.setItemText(0, _translate("Cite", "new line", None))
        self.separator.setItemText(1, _translate("Cite", "empty line", None))
        self.separator.setItemText(2, _translate("Cite", "bibitem/bibtex", None))
        self.label_22.setText(_translate("Cite", "Fetcher", None))
        self.batchFetcher.setItemText(0, _translate("Cite", "Batch", None))
        self.batchFetcher.setItemText(1, _translate("Cite", "MathSciNet", None))
        self.batchFetcher.setItemText(2, _translate("Cite", "zbMATH", None))
        self.batchFetcher.setItemText(3, _translate("Cite", "arXiv", None))
        self.label_23.setText(_translate("Cite", "Fetch", None))
        self.batchRun.setText(_translate("Cite", "All Entries", None))
        self.batchRunSelected.setText(_translate("Cite", "Selected", None))
        self.batchOpenInResults.setText(_translate("Cite", "Open in Saved:", None))
        self.batchOpenOptions.setItemText(0, _translate("Cite", "as is", None))
        self.batchOpenOptions.setItemText(1, _translate("Cite", "results", None))
        self.batchOpenOptions.setItemText(2, _translate("Cite", "unique", None))
        self.batchRemove.setText(_translate("Cite", "Remove:", None))
        self.batchRemoveOptions.setItemText(0, _translate("Cite", "unique", None))
        self.batchRemoveOptions.setItemText(1, _translate("Cite", "nonunique", None))
        self.batchRemoveOptions.setItemText(2, _translate("Cite", "queries/comments", None))
        self.batchRemoveOptions.setItemText(3, _translate("Cite", "comments", None))
        self.batchRemoveOptions.setItemText(4, _translate("Cite", "all but unique", None))
        self.batchRemoveOptions.setItemText(5, _translate("Cite", "all but not matched", None))
        self.batchRemoveOptions.setItemText(6, _translate("Cite", "all but nonunique", None))
        self.pushButton_5.setText(_translate("Cite", "Save LaTex/BibTex", None))
        self.pushButton_4.setText(_translate("Cite", "Load LaTex/BibTex", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.batchTab), _translate("Cite", "Batch", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("Cite", "Help", None))

