# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'citeGUI.ui'
#
# Created: Sun Nov 29 20:32:22 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Cite(object):
    def setupUi(self, Cite):
        Cite.setObjectName("Cite")
        Cite.resize(750, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Cite.sizePolicy().hasHeightForWidth())
        Cite.setSizePolicy(sizePolicy)
        Cite.setMinimumSize(QtCore.QSize(750, 500))
        self.centralWidget = QtWidgets.QWidget(Cite)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.searchTab = QtWidgets.QWidget()
        self.searchTab.setObjectName("searchTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.searchTab)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchQuery = QtWidgets.QPlainTextEdit(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchQuery.sizePolicy().hasHeightForWidth())
        self.searchQuery.setSizePolicy(sizePolicy)
        self.searchQuery.setMinimumSize(QtCore.QSize(0, 80))
        self.searchQuery.setMaximumSize(QtCore.QSize(16777215, 80))
        self.searchQuery.setObjectName("searchQuery")
        self.verticalLayout_2.addWidget(self.searchQuery)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.arxiv = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arxiv.sizePolicy().hasHeightForWidth())
        self.arxiv.setSizePolicy(sizePolicy)
        self.arxiv.setMinimumSize(QtCore.QSize(90, 0))
        self.arxiv.setObjectName("arxiv")
        self.horizontalLayout_4.addWidget(self.arxiv)
        self.arxivExport = QtWidgets.QPushButton(self.groupBox_5)
        self.arxivExport.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arxivExport.sizePolicy().hasHeightForWidth())
        self.arxivExport.setSizePolicy(sizePolicy)
        self.arxivExport.setMinimumSize(QtCore.QSize(60, 0))
        self.arxivExport.setObjectName("arxivExport")
        self.horizontalLayout_4.addWidget(self.arxivExport)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.msn = QtWidgets.QPushButton(self.groupBox_6)
        self.msn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msn.sizePolicy().hasHeightForWidth())
        self.msn.setSizePolicy(sizePolicy)
        self.msn.setMinimumSize(QtCore.QSize(100, 0))
        self.msn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.msn.setObjectName("msn")
        self.horizontalLayout_8.addWidget(self.msn)
        self.mrl = QtWidgets.QPushButton(self.groupBox_6)
        self.mrl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrl.sizePolicy().hasHeightForWidth())
        self.mrl.setSizePolicy(sizePolicy)
        self.mrl.setMinimumSize(QtCore.QSize(90, 0))
        self.mrl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.mrl.setObjectName("mrl")
        self.horizontalLayout_8.addWidget(self.mrl)
        self.mref = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mref.sizePolicy().hasHeightForWidth())
        self.mref.setSizePolicy(sizePolicy)
        self.mref.setMinimumSize(QtCore.QSize(60, 0))
        self.mref.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mref.setObjectName("mref")
        self.horizontalLayout_8.addWidget(self.mref)
        self.msnAuthor = QtWidgets.QPushButton(self.groupBox_6)
        self.msnAuthor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msnAuthor.sizePolicy().hasHeightForWidth())
        self.msnAuthor.setSizePolicy(sizePolicy)
        self.msnAuthor.setMinimumSize(QtCore.QSize(70, 0))
        self.msnAuthor.setMaximumSize(QtCore.QSize(70, 16777215))
        self.msnAuthor.setCheckable(False)
        self.msnAuthor.setObjectName("msnAuthor")
        self.horizontalLayout_8.addWidget(self.msnAuthor)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.zbl = QtWidgets.QPushButton(self.groupBox_7)
        self.zbl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zbl.sizePolicy().hasHeightForWidth())
        self.zbl.setSizePolicy(sizePolicy)
        self.zbl.setMinimumSize(QtCore.QSize(85, 0))
        self.zbl.setMaximumSize(QtCore.QSize(85, 16777215))
        self.zbl.setObjectName("zbl")
        self.horizontalLayout_10.addWidget(self.zbl)
        self.zblAuthor = QtWidgets.QPushButton(self.groupBox_7)
        self.zblAuthor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zblAuthor.sizePolicy().hasHeightForWidth())
        self.zblAuthor.setSizePolicy(sizePolicy)
        self.zblAuthor.setMinimumSize(QtCore.QSize(70, 0))
        self.zblAuthor.setMaximumSize(QtCore.QSize(70, 16777215))
        self.zblAuthor.setObjectName("zblAuthor")
        self.horizontalLayout_10.addWidget(self.zblAuthor)
        self.horizontalLayout.addWidget(self.groupBox_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_8 = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.openInResults = QtWidgets.QPushButton(self.groupBox_8)
        self.openInResults.setObjectName("openInResults")
        self.horizontalLayout_11.addWidget(self.openInResults)
        self.reformat = QtWidgets.QPushButton(self.groupBox_8)
        self.reformat.setObjectName("reformat")
        self.horizontalLayout_11.addWidget(self.reformat)
        self.showBibtex = QtWidgets.QPushButton(self.groupBox_8)
        self.showBibtex.setObjectName("showBibtex")
        self.horizontalLayout_11.addWidget(self.showBibtex)
        self.horizontalLayout_9.addWidget(self.groupBox_8)
        self.groupBox_10 = QtWidgets.QGroupBox(self.searchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.formatBibtex = QtWidgets.QPushButton(self.groupBox_10)
        self.formatBibtex.setObjectName("formatBibtex")
        self.horizontalLayout_12.addWidget(self.formatBibtex)
        self.allThree = QtWidgets.QPushButton(self.groupBox_10)
        self.allThree.setEnabled(True)
        self.allThree.setMinimumSize(QtCore.QSize(80, 0))
        self.allThree.setObjectName("allThree")
        self.horizontalLayout_12.addWidget(self.allThree)
        self.horizontalLayout_9.addWidget(self.groupBox_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.quickResults = QtWidgets.QTextBrowser(self.searchTab)
        self.quickResults.setReadOnly(True)
        self.quickResults.setOpenExternalLinks(True)
        self.quickResults.setObjectName("quickResults")
        self.verticalLayout_2.addWidget(self.quickResults)
        self.tabWidget.addTab(self.searchTab, "")
        self.resultsTab = QtWidgets.QWidget()
        self.resultsTab.setEnabled(True)
        self.resultsTab.setObjectName("resultsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.resultsTab)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.savedReformat = QtWidgets.QPushButton(self.resultsTab)
        self.savedReformat.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedReformat.sizePolicy().hasHeightForWidth())
        self.savedReformat.setSizePolicy(sizePolicy)
        self.savedReformat.setObjectName("savedReformat")
        self.horizontalLayout_13.addWidget(self.savedReformat)
        self.savedShowBibtex = QtWidgets.QPushButton(self.resultsTab)
        self.savedShowBibtex.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedShowBibtex.sizePolicy().hasHeightForWidth())
        self.savedShowBibtex.setSizePolicy(sizePolicy)
        self.savedShowBibtex.setObjectName("savedShowBibtex")
        self.horizontalLayout_13.addWidget(self.savedShowBibtex)
        self.saveLatex = QtWidgets.QPushButton(self.resultsTab)
        self.saveLatex.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveLatex.sizePolicy().hasHeightForWidth())
        self.saveLatex.setSizePolicy(sizePolicy)
        self.saveLatex.setObjectName("saveLatex")
        self.horizontalLayout_13.addWidget(self.saveLatex)
        self.saveBibtex = QtWidgets.QPushButton(self.resultsTab)
        self.saveBibtex.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBibtex.sizePolicy().hasHeightForWidth())
        self.saveBibtex.setSizePolicy(sizePolicy)
        self.saveBibtex.setObjectName("saveBibtex")
        self.horizontalLayout_13.addWidget(self.saveBibtex)
        self.loadBibtex = QtWidgets.QPushButton(self.resultsTab)
        self.loadBibtex.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBibtex.sizePolicy().hasHeightForWidth())
        self.loadBibtex.setSizePolicy(sizePolicy)
        self.loadBibtex.setObjectName("loadBibtex")
        self.horizontalLayout_13.addWidget(self.loadBibtex)
        self.openInBatch = QtWidgets.QPushButton(self.resultsTab)
        self.openInBatch.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openInBatch.sizePolicy().hasHeightForWidth())
        self.openInBatch.setSizePolicy(sizePolicy)
        self.openInBatch.setObjectName("openInBatch")
        self.horizontalLayout_13.addWidget(self.openInBatch)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.resultsTabs = QtWidgets.QTabWidget(self.resultsTab)
        self.resultsTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.resultsTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.resultsTabs.setDocumentMode(True)
        self.resultsTabs.setTabsClosable(True)
        self.resultsTabs.setMovable(True)
        self.resultsTabs.setTabBarAutoHide(False)
        self.resultsTabs.setObjectName("resultsTabs")
        self.emptyResults = QtWidgets.QWidget()
        self.emptyResults.setObjectName("emptyResults")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.emptyResults)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.emptyText = QtWidgets.QTextBrowser(self.emptyResults)
        self.emptyText.setEnabled(True)
        self.emptyText.setUndoRedoEnabled(False)
        self.emptyText.setReadOnly(True)
        self.emptyText.setObjectName("emptyText")
        self.horizontalLayout_3.addWidget(self.emptyText)
        self.resultsTabs.addTab(self.emptyResults, "")
        self.verticalLayout.addWidget(self.resultsTabs)
        self.tabWidget.addTab(self.resultsTab, "")
        self.optionsTab = QtWidgets.QWidget()
        self.optionsTab.setObjectName("optionsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.optionsTab)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(650, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keepBibitems = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepBibitems.sizePolicy().hasHeightForWidth())
        self.keepBibitems.setSizePolicy(sizePolicy)
        self.keepBibitems.setChecked(True)
        self.keepBibitems.setObjectName("keepBibitems")
        self.gridLayout_2.addWidget(self.keepBibitems, 0, 9, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 10, 1, 1)
        self.bibtexOut = QtWidgets.QCheckBox(self.groupBox_2)
        self.bibtexOut.setObjectName("bibtexOut")
        self.gridLayout_2.addWidget(self.bibtexOut, 0, 1, 1, 1)
        self.genBibitems = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genBibitems.sizePolicy().hasHeightForWidth())
        self.genBibitems.setSizePolicy(sizePolicy)
        self.genBibitems.setChecked(True)
        self.genBibitems.setObjectName("genBibitems")
        self.gridLayout_2.addWidget(self.genBibitems, 0, 8, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 3, 1, 1)
        self.sortBy = QtWidgets.QComboBox(self.groupBox_2)
        self.sortBy.setObjectName("sortBy")
        self.sortBy.addItem("")
        self.sortBy.addItem("")
        self.sortBy.addItem("")
        self.gridLayout_2.addWidget(self.sortBy, 0, 4, 1, 2)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        self.defaultArxiv = QtWidgets.QComboBox(self.groupBox_2)
        self.defaultArxiv.setEnabled(False)
        self.defaultArxiv.setObjectName("defaultArxiv")
        self.defaultArxiv.addItem("")
        self.defaultArxiv.addItem("")
        self.gridLayout_2.addWidget(self.defaultArxiv, 1, 2, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 7, 1, 1)
        self.defaultAMS = QtWidgets.QComboBox(self.groupBox_2)
        self.defaultAMS.setEnabled(False)
        self.defaultAMS.setObjectName("defaultAMS")
        self.defaultAMS.addItem("")
        self.defaultAMS.addItem("")
        self.defaultAMS.addItem("")
        self.gridLayout_2.addWidget(self.defaultAMS, 1, 8, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 6, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(650, 0))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.authorStyle = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorStyle.sizePolicy().hasHeightForWidth())
        self.authorStyle.setSizePolicy(sizePolicy)
        self.authorStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.authorStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.authorStyle.setObjectName("authorStyle")
        self.gridLayout_3.addWidget(self.authorStyle, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 4, 1, 1)
        self.journalStyle = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journalStyle.sizePolicy().hasHeightForWidth())
        self.journalStyle.setSizePolicy(sizePolicy)
        self.journalStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.journalStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.journalStyle.setText("")
        self.journalStyle.setObjectName("journalStyle")
        self.gridLayout_3.addWidget(self.journalStyle, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.titleStyle = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleStyle.sizePolicy().hasHeightForWidth())
        self.titleStyle.setSizePolicy(sizePolicy)
        self.titleStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.titleStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.titleStyle.setObjectName("titleStyle")
        self.gridLayout_3.addWidget(self.titleStyle, 0, 1, 1, 1)
        self.bibitemStyle = QtWidgets.QComboBox(self.groupBox_3)
        self.bibitemStyle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bibitemStyle.sizePolicy().hasHeightForWidth())
        self.bibitemStyle.setSizePolicy(sizePolicy)
        self.bibitemStyle.setObjectName("bibitemStyle")
        self.bibitemStyle.addItem("")
        self.bibitemStyle.addItem("")
        self.bibitemStyle.addItem("")
        self.bibitemStyle.addItem("")
        self.gridLayout_3.addWidget(self.bibitemStyle, 1, 6, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.volumeStyle = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeStyle.sizePolicy().hasHeightForWidth())
        self.volumeStyle.setSizePolicy(sizePolicy)
        self.volumeStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.volumeStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.volumeStyle.setObjectName("volumeStyle")
        self.gridLayout_3.addWidget(self.volumeStyle, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.numberStyle = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberStyle.sizePolicy().hasHeightForWidth())
        self.numberStyle.setSizePolicy(sizePolicy)
        self.numberStyle.setMinimumSize(QtCore.QSize(60, 0))
        self.numberStyle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.numberStyle.setObjectName("numberStyle")
        self.gridLayout_3.addWidget(self.numberStyle, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.bst = QtWidgets.QComboBox(self.groupBox_3)
        self.bst.setEnabled(False)
        self.bst.setObjectName("bst")
        self.bst.addItem("")
        self.bst.addItem("")
        self.gridLayout_3.addWidget(self.bst, 1, 3, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 5, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.searchArxiv = QtWidgets.QComboBox(self.groupBox)
        self.searchArxiv.setObjectName("searchArxiv")
        self.searchArxiv.addItem("")
        self.searchArxiv.addItem("")
        self.gridLayout.addWidget(self.searchArxiv, 12, 1, 1, 3)
        self.searchCount = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchCount.sizePolicy().hasHeightForWidth())
        self.searchCount.setSizePolicy(sizePolicy)
        self.searchCount.setMinimumSize(QtCore.QSize(50, 0))
        self.searchCount.setMaximumSize(QtCore.QSize(50, 16777215))
        self.searchCount.setMinimum(1)
        self.searchCount.setMaximum(999)
        self.searchCount.setProperty("value", 10)
        self.searchCount.setObjectName("searchCount")
        self.gridLayout.addWidget(self.searchCount, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(90, 0))
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(90, 0))
        self.label_16.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 12, 0, 1, 1)
        self.searchMRZbl = QtWidgets.QComboBox(self.groupBox)
        self.searchMRZbl.setObjectName("searchMRZbl")
        self.searchMRZbl.addItem("")
        self.searchMRZbl.addItem("")
        self.searchMRZbl.addItem("")
        self.searchMRZbl.addItem("")
        self.searchMRZbl.addItem("")
        self.searchMRZbl.addItem("")
        self.gridLayout.addWidget(self.searchMRZbl, 9, 1, 1, 3)
        self.searchIncludeDOIURL = QtWidgets.QComboBox(self.groupBox)
        self.searchIncludeDOIURL.setObjectName("searchIncludeDOIURL")
        self.searchIncludeDOIURL.addItem("")
        self.searchIncludeDOIURL.addItem("")
        self.searchIncludeDOIURL.addItem("")
        self.searchIncludeDOIURL.addItem("")
        self.gridLayout.addWidget(self.searchIncludeDOIURL, 10, 1, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(90, 0))
        self.label_15.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.searchDOIURL = QtWidgets.QComboBox(self.groupBox)
        self.searchDOIURL.setObjectName("searchDOIURL")
        self.searchDOIURL.addItem("")
        self.searchDOIURL.addItem("")
        self.searchDOIURL.addItem("")
        self.searchDOIURL.addItem("")
        self.searchDOIURL.addItem("")
        self.gridLayout.addWidget(self.searchDOIURL, 11, 1, 1, 3)
        self.searchMrefWithZbl = QtWidgets.QCheckBox(self.groupBox)
        self.searchMrefWithZbl.setChecked(True)
        self.searchMrefWithZbl.setObjectName("searchMrefWithZbl")
        self.gridLayout.addWidget(self.searchMrefWithZbl, 3, 0, 1, 2)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_9 = QtWidgets.QGroupBox(self.optionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.batchFindZbl = QtWidgets.QCheckBox(self.groupBox_9)
        self.batchFindZbl.setEnabled(False)
        self.batchFindZbl.setObjectName("batchFindZbl")
        self.gridLayout_5.addWidget(self.batchFindZbl, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(90, 0))
        self.label_20.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 2)
        self.batchCount = QtWidgets.QSpinBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchCount.sizePolicy().hasHeightForWidth())
        self.batchCount.setSizePolicy(sizePolicy)
        self.batchCount.setMinimumSize(QtCore.QSize(50, 0))
        self.batchCount.setMaximumSize(QtCore.QSize(50, 16777215))
        self.batchCount.setMinimum(1)
        self.batchCount.setMaximum(10)
        self.batchCount.setProperty("value", 3)
        self.batchCount.setObjectName("batchCount")
        self.gridLayout_5.addWidget(self.batchCount, 0, 2, 1, 1)
        self.batchDOIURL = QtWidgets.QComboBox(self.groupBox_9)
        self.batchDOIURL.setObjectName("batchDOIURL")
        self.gridLayout_5.addWidget(self.batchDOIURL, 6, 1, 1, 2)
        self.arxivFirst = QtWidgets.QCheckBox(self.groupBox_9)
        self.arxivFirst.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arxivFirst.sizePolicy().hasHeightForWidth())
        self.arxivFirst.setSizePolicy(sizePolicy)
        self.arxivFirst.setObjectName("arxivFirst")
        self.gridLayout_5.addWidget(self.arxivFirst, 1, 0, 1, 1)
        self.batchArxiv = QtWidgets.QComboBox(self.groupBox_9)
        self.batchArxiv.setObjectName("batchArxiv")
        self.gridLayout_5.addWidget(self.batchArxiv, 7, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(90, 0))
        self.label_18.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 4, 0, 1, 1)
        self.batchFindMR = QtWidgets.QCheckBox(self.groupBox_9)
        self.batchFindMR.setChecked(True)
        self.batchFindMR.setObjectName("batchFindMR")
        self.gridLayout_5.addWidget(self.batchFindMR, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(90, 0))
        self.label_19.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 5, 0, 1, 1)
        self.batchIncludeDOIURL = QtWidgets.QComboBox(self.groupBox_9)
        self.batchIncludeDOIURL.setObjectName("batchIncludeDOIURL")
        self.gridLayout_5.addWidget(self.batchIncludeDOIURL, 5, 1, 1, 2)
        self.batchMRZbl = QtWidgets.QComboBox(self.groupBox_9)
        self.batchMRZbl.setObjectName("batchMRZbl")
        self.gridLayout_5.addWidget(self.batchMRZbl, 4, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_9)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.tabWidget.addTab(self.optionsTab, "")
        self.batchTab = QtWidgets.QWidget()
        self.batchTab.setEnabled(True)
        self.batchTab.setObjectName("batchTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.batchTab)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.separator = QtWidgets.QComboBox(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separator.sizePolicy().hasHeightForWidth())
        self.separator.setSizePolicy(sizePolicy)
        self.separator.setMinimumSize(QtCore.QSize(130, 0))
        self.separator.setMaximumSize(QtCore.QSize(130, 16777215))
        self.separator.setObjectName("separator")
        self.separator.addItem("")
        self.separator.addItem("")
        self.separator.addItem("")
        self.horizontalLayout_2.addWidget(self.separator)
        self.label_22 = QtWidgets.QLabel(self.batchTab)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.batchFetcher = QtWidgets.QComboBox(self.batchTab)
        self.batchFetcher.setObjectName("batchFetcher")
        self.batchFetcher.addItem("")
        self.batchFetcher.addItem("")
        self.batchFetcher.addItem("")
        self.batchFetcher.addItem("")
        self.horizontalLayout_2.addWidget(self.batchFetcher)
        self.line_4 = QtWidgets.QFrame(self.batchTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.label_23 = QtWidgets.QLabel(self.batchTab)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.batchRun = QtWidgets.QPushButton(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRun.sizePolicy().hasHeightForWidth())
        self.batchRun.setSizePolicy(sizePolicy)
        self.batchRun.setMinimumSize(QtCore.QSize(100, 0))
        self.batchRun.setMaximumSize(QtCore.QSize(100, 16777215))
        self.batchRun.setObjectName("batchRun")
        self.horizontalLayout_2.addWidget(self.batchRun)
        self.batchRunSelected = QtWidgets.QPushButton(self.batchTab)
        self.batchRunSelected.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRunSelected.sizePolicy().hasHeightForWidth())
        self.batchRunSelected.setSizePolicy(sizePolicy)
        self.batchRunSelected.setMinimumSize(QtCore.QSize(100, 0))
        self.batchRunSelected.setMaximumSize(QtCore.QSize(100, 16777215))
        self.batchRunSelected.setObjectName("batchRunSelected")
        self.horizontalLayout_2.addWidget(self.batchRunSelected)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.batchOpenInResults = QtWidgets.QPushButton(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchOpenInResults.sizePolicy().hasHeightForWidth())
        self.batchOpenInResults.setSizePolicy(sizePolicy)
        self.batchOpenInResults.setMinimumSize(QtCore.QSize(120, 0))
        self.batchOpenInResults.setMaximumSize(QtCore.QSize(120, 16777215))
        self.batchOpenInResults.setObjectName("batchOpenInResults")
        self.horizontalLayout_7.addWidget(self.batchOpenInResults)
        self.batchOpenOptions = QtWidgets.QComboBox(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchOpenOptions.sizePolicy().hasHeightForWidth())
        self.batchOpenOptions.setSizePolicy(sizePolicy)
        self.batchOpenOptions.setMinimumSize(QtCore.QSize(80, 0))
        self.batchOpenOptions.setMaximumSize(QtCore.QSize(80, 16777215))
        self.batchOpenOptions.setObjectName("batchOpenOptions")
        self.batchOpenOptions.addItem("")
        self.batchOpenOptions.addItem("")
        self.batchOpenOptions.addItem("")
        self.horizontalLayout_7.addWidget(self.batchOpenOptions)
        self.batchRemove = QtWidgets.QPushButton(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRemove.sizePolicy().hasHeightForWidth())
        self.batchRemove.setSizePolicy(sizePolicy)
        self.batchRemove.setMinimumSize(QtCore.QSize(80, 0))
        self.batchRemove.setMaximumSize(QtCore.QSize(80, 16777215))
        self.batchRemove.setObjectName("batchRemove")
        self.horizontalLayout_7.addWidget(self.batchRemove)
        self.batchRemoveOptions = QtWidgets.QComboBox(self.batchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchRemoveOptions.sizePolicy().hasHeightForWidth())
        self.batchRemoveOptions.setSizePolicy(sizePolicy)
        self.batchRemoveOptions.setMinimumSize(QtCore.QSize(150, 0))
        self.batchRemoveOptions.setMaximumSize(QtCore.QSize(150, 16777215))
        self.batchRemoveOptions.setObjectName("batchRemoveOptions")
        self.batchRemoveOptions.addItem("")
        self.batchRemoveOptions.addItem("")
        self.batchRemoveOptions.addItem("")
        self.batchRemoveOptions.addItem("")
        self.batchRemoveOptions.addItem("")
        self.batchRemoveOptions.addItem("")
        self.batchRemoveOptions.addItem("")
        self.horizontalLayout_7.addWidget(self.batchRemoveOptions)
        self.line_5 = QtWidgets.QFrame(self.batchTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_7.addWidget(self.line_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.batchTab)
        self.pushButton_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.batchTab)
        self.pushButton_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.batchEdit = QtWidgets.QTextEdit(self.batchTab)
        self.batchEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.batchEdit.setObjectName("batchEdit")
        self.verticalLayout_7.addWidget(self.batchEdit)
        self.tabWidget.addTab(self.batchTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.helpTab)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.helpText = QtWidgets.QTextBrowser(self.helpTab)
        self.helpText.setOpenExternalLinks(True)
        self.helpText.setObjectName("helpText")
        self.verticalLayout_4.addWidget(self.helpText)
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        Cite.setCentralWidget(self.centralWidget)

        self.retranslateUi(Cite)
        self.tabWidget.setCurrentIndex(3)
        self.resultsTabs.setCurrentIndex(0)
        self.searchMRZbl.setCurrentIndex(3)
        self.searchIncludeDOIURL.setCurrentIndex(1)
        self.searchDOIURL.setCurrentIndex(3)
        self.batchMRZbl.setCurrentIndex(-1)
        self.separator.setCurrentIndex(2)
        self.batchOpenOptions.setCurrentIndex(2)
        self.batchRemoveOptions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Cite)

    def retranslateUi(self, Cite):
        _translate = QtCore.QCoreApplication.translate
        Cite.setWindowTitle(_translate("Cite", "Cite"))
        self.searchQuery.setToolTip(_translate("Cite", "<html><head/><body><p>Supports and/or/not operator, parentheses and field specifiers.</p><p>For example au:, ti:, py: denote title, author and publication year fields. For the complete list of fields see Help.</p><p>New line indicates a new field, which can sometimes be guessed. E.g. 2005-2011 or 2005 will be treated as publication year.</p><p>Operators and/or/not at the end or beginning of a line are treated as connectors for the whole fields/lines.</p><p>Fully formed LaTex citation or BibTex record can also be used.</p></body></html>"))
        self.groupBox_5.setTitle(_translate("Cite", "arXiv"))
        self.arxiv.setText(_translate("Cite", "arXiv front"))
        self.arxivExport.setText(_translate("Cite", "Export"))
        self.groupBox_6.setTitle(_translate("Cite", "MSN"))
        self.msn.setText(_translate("Cite", "MathSciNet"))
        self.mrl.setText(_translate("Cite", "MRLookup"))
        self.mref.setText(_translate("Cite", "MRef"))
        self.msnAuthor.setText(_translate("Cite", "Author"))
        self.groupBox_7.setTitle(_translate("Cite", "Zentralblatt"))
        self.zbl.setText(_translate("Cite", "zbMATH"))
        self.zblAuthor.setText(_translate("Cite", "Author"))
        self.groupBox_8.setTitle(_translate("Cite", "Last result"))
        self.openInResults.setText(_translate("Cite", "Open in Saved"))
        self.reformat.setText(_translate("Cite", "Reformat"))
        self.showBibtex.setText(_translate("Cite", "Show  BibTex"))
        self.groupBox_10.setTitle(_translate("Cite", "Other"))
        self.formatBibtex.setText(_translate("Cite", "BibTex on query"))
        self.allThree.setText(_translate("Cite", "arXiv + MSN + Zbl"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchTab), _translate("Cite", "Search"))
        self.savedReformat.setText(_translate("Cite", "Reformat"))
        self.savedShowBibtex.setText(_translate("Cite", "Show BibTex"))
        self.saveLatex.setText(_translate("Cite", "Save LaTeX"))
        self.saveBibtex.setText(_translate("Cite", "Save BibTex"))
        self.loadBibtex.setText(_translate("Cite", "Load BibTex"))
        self.openInBatch.setText(_translate("Cite", "Open in Batch"))
        self.emptyText.setHtml(_translate("Cite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click &quot;Open in Saved&quot; in the search or batch tab for the search results to appear here.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.emptyResults), _translate("Cite", "No results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), _translate("Cite", "Saved"))
        self.groupBox_2.setTitle(_translate("Cite", "General"))
        self.keepBibitems.setText(_translate("Cite", "keep existing"))
        self.bibtexOut.setText(_translate("Cite", "BibTex output"))
        self.genBibitems.setText(_translate("Cite", "generate"))
        self.label_12.setText(_translate("Cite", "Bibitems:"))
        self.label_13.setText(_translate("Cite", "Default arXiv"))
        self.label_17.setText(_translate("Cite", "Sort"))
        self.sortBy.setItemText(0, _translate("Cite", "newest first"))
        self.sortBy.setItemText(1, _translate("Cite", "oldest first"))
        self.sortBy.setItemText(2, _translate("Cite", "by name"))
        self.defaultArxiv.setItemText(0, _translate("Cite", "UCDavis front"))
        self.defaultArxiv.setItemText(1, _translate("Cite", "export"))
        self.label_3.setText(_translate("Cite", "Default MSN"))
        self.defaultAMS.setItemText(0, _translate("Cite", "Automatic"))
        self.defaultAMS.setItemText(1, _translate("Cite", "MathSciNet"))
        self.defaultAMS.setItemText(2, _translate("Cite", "MRLookup"))
        self.groupBox_3.setTitle(_translate("Cite", "Style"))
        self.authorStyle.setText(_translate("Cite", "textbf"))
        self.label_9.setText(_translate("Cite", "Volume"))
        self.label_8.setText(_translate("Cite", "Journal"))
        self.label_6.setText(_translate("Cite", "Title"))
        self.titleStyle.setText(_translate("Cite", "textit"))
        self.bibitemStyle.setItemText(0, _translate("Cite", "{initials}"))
        self.bibitemStyle.setItemText(1, _translate("Cite", "[initials]{initials}"))
        self.bibitemStyle.setItemText(2, _translate("Cite", "{id}"))
        self.bibitemStyle.setItemText(3, _translate("Cite", "[initials]{id}"))
        self.label_7.setText(_translate("Cite", "Author"))
        self.volumeStyle.setText(_translate("Cite", "textbf"))
        self.label_10.setText(_translate("Cite", "Number"))
        self.numberStyle.setText(_translate("Cite", "textit"))
        self.label_5.setText(_translate("Cite", "Order"))
        self.bst.setItemText(0, _translate("Cite", "amsplain"))
        self.bst.setItemText(1, _translate("Cite", "plain"))
        self.label_11.setText(_translate("Cite", "Labels"))
        self.groupBox.setTitle(_translate("Cite", "Search options"))
        self.searchArxiv.setItemText(0, _translate("Cite", "Include"))
        self.searchArxiv.setItemText(1, _translate("Cite", "Exclude"))
        self.label.setText(_translate("Cite", "Maximal number of  matches"))
        self.label_14.setText(_translate("Cite", "MR# / Zbl#"))
        self.label_16.setText(_translate("Cite", "arXiv#"))
        self.searchMRZbl.setItemText(0, _translate("Cite", "Both"))
        self.searchMRZbl.setItemText(1, _translate("Cite", "MR#"))
        self.searchMRZbl.setItemText(2, _translate("Cite", "Zbl#"))
        self.searchMRZbl.setItemText(3, _translate("Cite", "Zbl# if no MR#"))
        self.searchMRZbl.setItemText(4, _translate("Cite", "MR# if no Zbl#"))
        self.searchMRZbl.setItemText(5, _translate("Cite", "Neither"))
        self.searchIncludeDOIURL.setItemText(0, _translate("Cite", "Include"))
        self.searchIncludeDOIURL.setItemText(1, _translate("Cite", "Only if no MR#/Zbl#"))
        self.searchIncludeDOIURL.setItemText(2, _translate("Cite", "Only if no MR#/Zbl#/arXiv#"))
        self.searchIncludeDOIURL.setItemText(3, _translate("Cite", "Exclude"))
        self.label_15.setText(_translate("Cite", "DOI# / URL"))
        self.searchDOIURL.setItemText(0, _translate("Cite", "Both"))
        self.searchDOIURL.setItemText(1, _translate("Cite", "DOI#"))
        self.searchDOIURL.setItemText(2, _translate("Cite", "URL"))
        self.searchDOIURL.setItemText(3, _translate("Cite", "URL if different than DOI#"))
        self.searchDOIURL.setItemText(4, _translate("Cite", "DOI# as URL"))
        self.searchMrefWithZbl.setText(_translate("Cite", "MRef with zbMATH"))
        self.groupBox_9.setTitle(_translate("Cite", "Batch/Terminal options"))
        self.batchFindZbl.setText(_translate("Cite", "try to find Zbl#"))
        self.label_20.setText(_translate("Cite", "arXiv#"))
        self.label_2.setText(_translate("Cite", "Maximal number of matches"))
        self.arxivFirst.setText(_translate("Cite", "arXiv first"))
        self.label_18.setText(_translate("Cite", "MR# / Zbl#"))
        self.batchFindMR.setText(_translate("Cite", "try to find MR#"))
        self.label_19.setText(_translate("Cite", "DOI# / URL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), _translate("Cite", "Options"))
        self.label_21.setText(_translate("Cite", "Separator"))
        self.separator.setItemText(0, _translate("Cite", "new line"))
        self.separator.setItemText(1, _translate("Cite", "empty line"))
        self.separator.setItemText(2, _translate("Cite", "bibitem/bibtex"))
        self.label_22.setText(_translate("Cite", "Fetcher"))
        self.batchFetcher.setItemText(0, _translate("Cite", "Batch"))
        self.batchFetcher.setItemText(1, _translate("Cite", "MathSciNet"))
        self.batchFetcher.setItemText(2, _translate("Cite", "zbMATH"))
        self.batchFetcher.setItemText(3, _translate("Cite", "arXiv"))
        self.label_23.setText(_translate("Cite", "Fetch"))
        self.batchRun.setText(_translate("Cite", "All Entries"))
        self.batchRunSelected.setText(_translate("Cite", "Selected"))
        self.batchOpenInResults.setText(_translate("Cite", "Open in Saved:"))
        self.batchOpenOptions.setItemText(0, _translate("Cite", "as is"))
        self.batchOpenOptions.setItemText(1, _translate("Cite", "results"))
        self.batchOpenOptions.setItemText(2, _translate("Cite", "unique"))
        self.batchRemove.setText(_translate("Cite", "Remove:"))
        self.batchRemoveOptions.setItemText(0, _translate("Cite", "unique"))
        self.batchRemoveOptions.setItemText(1, _translate("Cite", "nonunique"))
        self.batchRemoveOptions.setItemText(2, _translate("Cite", "queries/comments"))
        self.batchRemoveOptions.setItemText(3, _translate("Cite", "comments"))
        self.batchRemoveOptions.setItemText(4, _translate("Cite", "all but unique"))
        self.batchRemoveOptions.setItemText(5, _translate("Cite", "all but not matched"))
        self.batchRemoveOptions.setItemText(6, _translate("Cite", "all but nonunique"))
        self.pushButton_5.setText(_translate("Cite", "Save LaTex/BibTex"))
        self.pushButton_4.setText(_translate("Cite", "Load LaTex/BibTex"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.batchTab), _translate("Cite", "Batch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("Cite", "Help"))

