#!/bin/bash
# this should be able to execute cite.py
RESOURCEPATH="/Applications/Cite.app/Contents/Resources"

export PATH="$PATH:/usr/texbin:/Library/TeX/texbin:"
export PYTHONPATH="$RESOURCEPATH/lib/python2.7/lib-dynload:$PYTHONPATH"
# export DYLD_PRINT_LIBRARIES=1
export DYLD_FRAMEWORK_PATH="$RESOURCEPATH/../Frameworks:$DYLD_FRAMEWORK_PATH"
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/usr/lib:
python cite.py $@
